# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
name: skeleton
vendor: vmware
version: 1.0.0
vcdVersion: 10.4.1
friendlyName: Skeleton Starter Kit
description: Showcase the multi-instance add-on flavor with unique elements for each instance

inputs:
  - name: provider-business-scope-property
    title: Business Scope
    required: true
    description: Define the business and operational scopes of the add-on instance
    minLength: 2
    maxLength: 24
  - name: password
    # Secure property 
    title: Password
    required: true
    description: The password for the new local Cloud Director account to be created and linked to a business scope.
    secure: true
    minLength: 8
    maxLength: 16
  - name: certificate
    title: Certificate
    type: String
    view: multiline
    secure: true
  - name: justification
    # Property visible only on delete operation
    title: Justification
    type: String
    description: Why delete this Solution instance?
    delete: true
    minLength: 5
    maxLength: 256


policies:
  # Enable the add-on to be deployed in multiple instances
  supportsMultipleInstances: true

triggers:
  # Enable a single actions to be called on PreCreate and PostDelete events
  - event: PreCreate
    action: actions/multipurposeaction
    timeout: 30
  - event: PostDelete
    action: actions/multipurposeaction
    timeout: 30
  - event: PreScope
    action: actions/multipurposeaction
    timeout: 30


operations:
  - name: updateCloudDirectorCertificate
    description: Add the current Cloud Director certificate into the trusted store
    friendlyName: Trust Current Cloud Director Certificate
    action: actions/multipurposeaction
    timeout: 10
  - name: updateTrustedStore
    description: Add a certificate into the trusted store
    friendlyName: Trust Certificate
    inputs:
      - name: certificate
        title: Certificate
        type: String
        view: multiline
        secure: true
    timeout: 10
    action: actions/multipurposeaction

elements:
  - name: ui
    # Immutable element, shared across all instances
    description: User interface
    type: ui-plugin
    spec:
      publish:
        provider: true
        tenants: true
        solutionLandingZone: true
    triggers:
      - event: PreScope
        action: actions/multipurposeaction
        timeout: 30
  - name: db-schemas
    # Immutable element, shared across all instances
    description: Business Objects Schemas
    type: defined-entity
  - name: rights
    # Mutable element, it needs to define a unique specification for each add-on instance
    description: Business objects rights
    type: rights-bundle
    spec:
      name: 'Skeleton-{{ instance `name` }}'
      description: This rights bundle is created by Skeleton Add-On
      publish:
        solutionLandingZone: true
      rights:
        - urn:vcloud:type:vmware:skeleton_database_entity
        - urn:vcloud:type:vmware:skeleton_database_entity:admin
  - name: role
    # Mutable element, it needs to define a unique specification for each add-on instance
    description: Business objects role
    type: role
    spec:
      name: 'Skeleton-{{ instance `name` }}'
      description: This role is created by Skeleton Add-On
      global: false
      systemScope: false
      publish: 
        solutionLandingZone: true
      rights:
        - urn:vcloud:type:vmware:skeleton_database_entity
        - urn:vcloud:type:vmware:skeleton_database_entity:admin
  - name: cloud-director-user
    # Mutable element, it needs to define a unique specification for each add-on instance
    description: User interacting with Cloud Director from backend
    type: user
    spec:
      username: 'sva.{{ property `provider-business-scope-property` }}'
      password: '{{ property `password` }}'
      fullName: Skeleton backend system account
      description: 'User sva.{{ property `provider-business-scope-property` }} with role {{ property `role.name` }}'
      roleName: '{{ property `role.name` }}'
      systemScope: false
    triggers:
      - event: PostCreate
        # This action will output property "api-token" under the element
        action: actions/multipurposeaction
        timeout: 30
  - name: 'backend-appliance'
    # Mutable element, it needs to define a unique specification for each add-on instance
    description: Backend processor of business objects
    type: vapp
    spec:
      # When the 'name' property is skipped for vApps, the SDK will generate a unique name
      ovfProperties:
        - key: provider-business-scope-property
          value: '{{ property `provider-business-scope-property` }}'
        - key: cloud-director-host
          value: '{{ vcd `host` }}'
        - key: cloud-director-host-certificates
          value: '{{ vcd `certificates` }}'
        - key: api-token
          value: '{{ property `api-token` }}'
      hardwareCustomization:
        numberOfCpus: 1
        memorySize: 512
      networks:
        - primary: true
          capabilities: []
      readyCondition:
        # The "Ready" condition waits for listed properties to have any value, or a specific value if defined.
        # A property can be the "ip" of the virtual machine or any of the available ExtraConfig properties.
        #
        # Example: Waiting for the virtual machine to be assigned an IP address
        # "ip":
        #
        # Note: This is a dummy vApp and will not allocate any IP.
      timeoutMinutes: 10
